# Generated by Django 5.2.8 on 2026-01-28 10:53

import django.db.models.deletion
from django.db import migrations, models

import citations.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('acronym', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=120)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('title', models.CharField(max_length=300)),
                ('partieset', models.TextField()),
                ('DOI', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FundingStreams',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('affiliation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='citations.institutions')),
            ],
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('first_name', models.CharField(editable=False, max_length=30)),
                ('last_name', models.CharField(editable=False, max_length=30)),
                ('middle_names', models.CharField(blank=True, editable=False, max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('orcid', models.CharField(blank=True, max_length=19, validators=[citations.validators.validate_orcid])),
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('affiliations', models.ManyToManyField(blank=True, to='citations.institutions')),
            ],
        ),
        migrations.CreateModel(
            name='Citations',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('version', models.IntegerField()),
                ('abstract', models.TextField()),
                ('drs_url', models.CharField()),
                ('doi_url', models.CharField()),
                ('rights', models.CharField(max_length=30)),
                ('license', models.TextField()),
                ('funders', models.ManyToManyField(blank=True, null=True, to='citations.fundingstreams')),
                ('institutions', models.ManyToManyField(blank=True, null=True, to='citations.institutions')),
                ('contacts', models.ManyToManyField(blank=True, null=True, related_name='contact_parties', to='citations.parties')),
                ('primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_party', to='citations.parties')),
                ('cites', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cites', to='citations.references')),
                ('is_cited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_cited_by', to='citations.references')),
                ('is_referenced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_referenced_by', to='citations.references')),
            ],
        ),
    ]
