# Generated by Django 5.2.8 on 2026-04-14 10:25

import django.db.models.deletion
from django.db import migrations, models

import citations.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institutions",
            fields=[
                ("name", models.CharField(max_length=120)),
                ("acronym", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=120)),
                (
                    "id",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="References",
            fields=[
                ("title", models.CharField(max_length=300)),
                ("citeas", models.TextField()),
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundingStreams",
            fields=[
                ("name", models.CharField(max_length=120)),
                (
                    "id",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                (
                    "affiliation",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="citations.institutions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parties",
            fields=[
                ("first_name", models.CharField(editable=False, max_length=30)),
                ("last_name", models.CharField(editable=False, max_length=30)),
                (
                    "middle_names",
                    models.CharField(blank=True, editable=False, max_length=60),
                ),
                ("email", models.CharField(max_length=100)),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        max_length=19,
                        validators=[citations.validators.validate_orcid],
                    ),
                ),
                ("id", models.CharField(primary_key=True, serialize=False)),
                (
                    "affiliations",
                    models.ManyToManyField(blank=True, to="citations.institutions"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Citations",
            fields=[
                (
                    "id",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300
                    ),
                ),
                ("version", models.IntegerField()),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                ("abstract", models.TextField()),
                ("drs_url", models.CharField()),
                ("doi_url", models.CharField()),
                ("rights", models.CharField(max_length=30)),
                ("license", models.TextField()),
                ("editable", models.BooleanField(default=True)),
                ("published", models.BooleanField(default=False)),
                ("mip_era", models.CharField(default="unknown", max_length=30)),
                ("activity_id", models.CharField(default="unknown", max_length=30)),
                ("institution_id", models.CharField(default="unknown", max_length=30)),
                ("source_id", models.CharField(default="unknown", max_length=30)),
                ("experiment_id", models.CharField(default="unknown", max_length=30)),
                (
                    "funders",
                    models.ManyToManyField(
                        blank=True, null=True, to="citations.fundingstreams"
                    ),
                ),
                (
                    "institutions",
                    models.ManyToManyField(
                        blank=True, null=True, to="citations.institutions"
                    ),
                ),
                (
                    "contacts",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="contact_parties",
                        to="citations.parties",
                    ),
                ),
                (
                    "primary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_party",
                        to="citations.parties",
                    ),
                ),
                (
                    "cites",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="cites",
                        to="citations.references",
                    ),
                ),
                (
                    "is_cited_by",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="is_cited_by",
                        to="citations.references",
                    ),
                ),
                (
                    "is_referenced_by",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="is_referenced_by",
                        to="citations.references",
                    ),
                ),
            ],
        ),
    ]
