# Generated by Django 5.2.8 on 2025-11-26 10:28

import citations.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('acronym', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=120, validators=[citations.validators.validate_country])),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('authorset', models.TextField()),
                ('DOI', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FundingStreams',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citations.institutions')),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('orcid', models.CharField(blank=True, max_length=19, validators=[citations.validators.validate_orcid])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('affiliations', models.ManyToManyField(blank=True, to='citations.institutions')),
            ],
        ),
        migrations.CreateModel(
            name='Citations',
            fields=[
                ('name', models.CharField(max_length=300)),
                ('abstract', models.TextField()),
                ('drs_url', models.CharField()),
                ('doi_url', models.CharField()),
                ('rights', models.CharField(max_length=30)),
                ('license', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contacts', models.ManyToManyField(related_name='contact_authors', to='citations.authors')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_author', to='citations.authors')),
                ('funders', models.ManyToManyField(to='citations.fundingstreams')),
                ('institutions', models.ManyToManyField(to='citations.institutions')),
                ('cites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cites', to='citations.references')),
                ('is_cited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_cited_by', to='citations.references')),
                ('is_referenced_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_referenced_by', to='citations.references')),
            ],
        ),
    ]
