# Generated by Django 5.2.8 on 2026-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citations',
            name='domain_id',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
