# Generated by Django 5.2.8 on 2026-02-18 11:19

from django.db import migrations, models


def extract_component(apps, schema_editor):
    Citations = apps.get_model('citations','Citations')
    for citation in Citations.objects.all().iterator():
        citation.mip_era, citation.activity_id, citation.institution_id, \
            citation.source_id, citation.experiment_id = citation.title.split('_')[:5]
        citation.save()

def revert_func():
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citations',
            name='activity_id',
            field=models.CharField(null=True, max_length=30),
        ),
        migrations.AddField(
            model_name='citations',
            name='experiment_id',
            field=models.CharField(null=True, max_length=30),
        ),
        migrations.AddField(
            model_name='citations',
            name='institution_id',
            field=models.CharField(null=True, max_length=30),
        ),
        migrations.AddField(
            model_name='citations',
            name='mip_era',
            field=models.CharField(null=True, max_length=30),
        ),
        migrations.AddField(
            model_name='citations',
            name='source_id',
            field=models.CharField(null=True, max_length=30),
        ),
        migrations.RunPython(extract_component, revert_func),
        migrations.AlterField(
            model_name='citations',
            name='activity_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='citations',
            name='experiment_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='citations',
            name='institution_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='citations',
            name='mip_era',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='citations',
            name='source_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='citations',
            name='editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='citations',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
