# Generated by Django 5.2.8 on 2026-02-18 11:42

import citations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0002_citations_activity_id_citations_editable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='activity_id',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='citations',
            name='experiment_id',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='citations',
            name='institution_id',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='citations',
            name='mip_era',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='citations',
            name='source_id',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='citations',
            name='title',
            field=models.CharField(max_length=300, validators=[citations.validators.validate_title]),
        ),
    ]
