# Generated by Django 5.2.8 on 2026-03-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0003_alter_citations_activity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citations',
            name='primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_party', to='citations.parties'),
        ),
        migrations.AlterField(
            model_name='fundingstreams',
            name='id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
