# Generated by Django 5.2.8 on 2026-04-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0004_alter_citations_primary_alter_fundingstreams_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='references',
            old_name='partieset',
            new_name='citeas',
        ),
        migrations.AlterField(
            model_name='citations',
            name='primary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_party', to='citations.parties'),
        ),
    ]
