# Generated by Django 5.2.8 on 2026-05-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citations", "0004_alter_references_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citations",
            name="publication_year",
        ),
        migrations.AddField(
            model_name="citations",
            name="publication_timestamp",
            field=models.CharField(blank=True, null=True),
        ),
    ]
