# Generated by Django 5.2.8 on 2026-04-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0005_rename_partieset_references_citeas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citations',
            name='cites',
        ),
        migrations.RemoveField(
            model_name='citations',
            name='is_cited_by',
        ),
        migrations.RemoveField(
            model_name='citations',
            name='is_referenced_by',
        ),
        migrations.AddField(
            model_name='citations',
            name='cites',
            field=models.ManyToManyField(blank=True, null=True, related_name='cites', to='citations.references'),
        ),
        migrations.AddField(
            model_name='citations',
            name='is_cited_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='is_cited_by', to='citations.references'),
        ),
        migrations.AddField(
            model_name='citations',
            name='is_referenced_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='is_referenced_by', to='citations.references'),
        ),
    ]
