# Generated by Django 5.2.8 on 2026-06-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citations", "0005_remove_citations_publication_year_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="citations",
            old_name="mip_era",
            new_name="project_id",
        ),
    ]
