# Generated by Django 5.2.8 on 2026-08-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citations", "0006_rename_mip_era_citations_project_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedRequests",
            fields=[
                (
                    "id",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                ("reason", models.TextField()),
            ],
        ),
    ]
