# Generated by Django 5.2.8 on 2026-04-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0006_remove_citations_cites_remove_citations_is_cited_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='references',
            old_name='DOI',
            new_name='id',
        ),
    ]
