# Generated by Django 5.2.8 on 2026-08-12 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citations", "0007_failedrequests"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitationParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "citation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="citations.citations",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="citations.parties",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
