# Generated by Django 5.2.8 on 2026-04-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0007_rename_doi_references_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='citations',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
