# Generated by Django 5.2.8 on 2026-08-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citations", "0009_citationparty_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citationparty",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
