# Generated by Django 5.2.8 on 2026-08-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citations", "0010_alter_citationparty_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListenerPause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pause_listener", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Pause Listener",
            },
        ),
    ]
