# Generated by Django 5.2.8 on 2026-09-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citations", "0011_listenerpause"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutions",
            name="acronym",
            field=models.CharField(max_length=30),
        ),
    ]
