# Generated by Django 5.2.8 on 2026-09-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citations", "0012_alter_institutions_acronym"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditorPause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pause_editor", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Pause Edits",
            },
        ),
    ]
