"""
Django settings for citation_site project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'citations',
    'rest_framework',
    'rest_framework.authtoken',
    "fwtheme_django_ceda_serv",
    "fwtheme_django",
    "cookielaw",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'citation_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'citation_site.wsgi.application'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    }
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

try:
    from .settings_local import *
except ImportError:
    CV_REPO = None
    DEBUG = True

SITE_ID = 1

CEDA_INFO = """
This record was created via the Citation Service, maintained and hosted on the CEDA-JASMIN Infrastructure.
"""

LICENSE_TEXT = {
    'CMIP7'.lower():"CC-BY-4.0; CMIP7 data produced by INSTITUTION_ID " \
        "is licensed under a Creative Commons Attribution 4.0 International License " \
        "[(https://creativecommons.org/licenses/by/4.0)](https://creativecommons.org/licenses/by/4.0). Consult " \
        "[https://wcrp-cmip.github.io/cmip7-guidance/docs/CMIP7/Guidance_for_users/#2-terms-of-use-and-citations-requirements]" \
        "(https://wcrp-cmip.github.io/cmip7-guidance/docs/CMIP7/Guidance_for_users/#2-terms-of-use-and-citations-requirements) " \
        "for terms of use governing CMIP7 output, including citation requirements and proper acknowledgment. " \
        "The data producers and data providers make no warranty, either express or implied, including, but not " \
        "limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising " \
        "from the supply of the information (including any liability arising in negligence) are excluded to the " \
        "fullest extent permitted by law.",
    'CMIP6Plus'.lower(): "CC-BY-4.0; CMIP6Plus model data produced by INSTITUTION_ID " \
        "is licensed under a Creative Commons Attribution 4.0 International License " \
        "[(https://creativecommons.org/licenses/by/4.0)](https://creativecommons.org/licenses/by/4.0). Consult " \
        "[https://pcmdi.llnl.gov/CMIP6Plus/TermsOfUse](https://pcmdi.llnl.gov/CMIP6Plus/TermsOfUse) for terms of use governing " \
        "CMIP6Plus output, including citation requirements and proper acknowledgment. " \
        "The data producers and data providers make no warranty, either express or implied, " \
        "including, but not limited to, warranties of merchantability and fitness for a " \
        "particular purpose. All liabilities arising from the supply of the information " \
        "(including any liability arising in negligence) are excluded to the fullest " \
        "extent permitted by law.",
    'CORDEX-CMIP6'.lower():"CC-BY-4.0; CORDEX-CMIP6 data produced by INSTITUTION_ID " \
        "is licensed under a Creative Commons Attribution 4.0 International License " \
        "[(https://creativecommons.org/licenses/by/4.0)](https://creativecommons.org/licenses/by/4.0). Consult " \
        "[https://cordex.org/data-access/cordex-cmip6-data/cordex-cmip6-terms-of-use]"
        "(https://cordex.org/data-access/cordex-cmip6-data/cordex-cmip6-terms-of-use) " \
        "for terms of use governing CORDEX-CMIP6 output, including citation requirements " \
        "and proper acknowledgment. The data producers and data providers make no warranty, " \
        "either express or implied, including, but not limited to, warranties of " \
        "merchantability and fitness for a particular purpose. All liabilities arising " \
        "from the supply of the information (including any liability arising in negligence) " \
        "are excluded to the fullest extent permitted by law."
}


GENERAL_INFO = {
    'CMIP7'.lower():"CMIP7 is a project of the [World Climate Research Programme " \
        "(WCRP)](https://www.wcrp-climate.org/), providing climate projections " \
        "to understand past, present, and future climate changes. It is part of the " \
        "[WCRP Earth System Modelling and Observations (ESMO) Core Project](https://" \
        "wcrp-esmo.org/), which was formed to coordinate all modelling, data, and " \
        "observation activities across WCRP and its key partners. Further details can " \
        "be found [here](https://www.wcrp-cmip.org/cmip-overview/) and in the [CMIP7 " \
        "Guidance pages](https://wcrp-cmip.github.io/cmip7-guidance/). Parties using CMIP " \
        "data should ensure they have read the [WCRP CMIP (2026) CMIP Data Disclaimer](" \
        "https://doi.org/10.5281/zenodo.18155119).",
    'CMIP6Plus'.lower():"CMIP Phase 6 Plus (CMIP6Plus) is a continuity activity that enables " \
        "modelling groups to contribute to projects initiated post-CMIP6 but before processes " \
        "for registering CMIP7 community MIPs and experiments is available. CMIP6Plus is supported by the " \
        "WCRP-ESMO Infrastructure Panel alongside other activities and will remain open until " \
        "CMIP7 procedures fully support the establishment of community MIPs and their data " \
        "requirements. Further information can be found [here](https://www.wcrp-cmip.org/cmip-phases/cmip6plus/). " \
        "Parties using CMIP data should ensure they have read the [WCRP CMIP (2026) CMIP Data Disclaimer](" \
        "https://doi.org/10.5281/zenodo.18155119).",
    'CORDEX-CMIP6'.lower(): "CORDEX is a [World Climate Research Programme (WCRP)]" \
        "(https://www.wcrp-climate.org/) initiative that advances the science and " \
        "application of regional climate downscaling by coordinating experiments " \
        "across fourteen continental domains and fostering related strategic " \
        "activities and partnerships. It provides regional climate projections " \
        "(driven by CMIP projections) to support the understanding of recent and "\
        "future regional climate change. CORDEX contributes to the [Regional " \
        "Information for Society (RIfS)](https://www.wcrp-rifs.org/) Core Project. " \
        "Users of CORDEX data should be familiar with the [CORDEX Terms of Use](" \
        "https://cordex.org/data-access/cordex-cmip6-data/cordex-cmip6-terms-of-use/)." \
        " A list of institutions contributing to CORDEX is available [here](" \
        "https://wcrp-cordex.github.io/cordex-cmip6-cv/CORDEX-CMIP6_institution_id.html)."
}

DEFAULT_RIGHTS = 'CC-BY-4.0'

RIGHTS_MAP = {
    "CC-BY-4.0": ('https://creativecommons.org/licenses/by/4.0/','Creative Commons Attribution 4.0 International License')
}