"""
Django settings for citation_site project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'citations',
    'rest_framework',
    'rest_framework.authtoken',
    "fwtheme_django_ceda_serv",
    "fwtheme_django",
    "cookielaw",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'citation_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'citation_site.wsgi.application'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ]
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    }
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

try:
    from .settings_local import *
except ImportError:
    CV_REPO = None
    DEBUG = True

SITE_ID = 1

CEDA_INFO = """
This record was created via the Citation Service, maintained and hosted on the CEDA-JASMIN Infrastructure.
"""

LICENSE = {
    'CMIP7'.lower():'',
    'CMIP6Plus'.lower():'',
    'CORDEX-CMIP6'.lower():''
}


GENERAL_INFO = {
    'CMIP7'.lower():"CMIP7 is a project of the World Climate Research Programme (WCRP)," \
        " coordinated by the Working Group on Coupled Modelling (WGCM)." \
        " Phase 7 builds on previous phases executed under the leadership of the" \
        " Program for Climate Model Diagnosis and Intercomparison (PCMDI)"\
        " and relies on the Earth System Grid Federation (ESGF) and the Centre for" \
        " Environmental Data Analysis (CEDA) along with numerous related activities" \
        " for implementation.",
    'CMIP6Plus'.lower():"CMIP Phase 6 Plus (CMIP6Plus) is a continuity activity that enables" \
        " modelling groups to contribute to projects initiated post-CMIP6 but before" \
        " the CMIP7 infrastructure and experiment design is available. Unlike CMIP6" \
        " and CMIP7, CMIP6Plus has no coordinated or managed Data Request, instead" \
        " CMIP6Plus MIPs coordinate the list of variables contributed by modelling" \
        " groups independently. CMIP6Plus controlled vocabularies (CVs) are project" \
        " specific, CMIP6Plus CVs for activity, experiment and model (source_id) are" \
        " listed in the CMIP6Plus_CVs github repository.",
    'CORDEX-CMIP6'.lower(): "CORDEX is a programme of the World Climate Research Programme" \
        " (WCRP), coordinated under the umbrella of the Regional Information for" \
        " Society (RIfS). CORDEX-CMIP6 builds on the work of the 6th phase of the" \
        " Coupled Model Intercomparison Project (CMIP6) and the European Centre for" \
        " Medium-Range Weather Forecasts (ECMWF) ERA5 reanalysis and relies on the" \
        " Earth System Grid Federation (ESGF) and the Centre for Environmental Data" \
        " Analysis (CEDA) along with numerous related activities" \
        " for implementation."
}

DEFAULT_RIGHTS = 'CC-BY-4.0'

RIGHTS_MAP = {
    "CC-BY-4.0": ('https://creativecommons.org/licenses/by/4.0/','Creative Commons Attribution 4.0 International License')
}